### ISSUE TITLE
Where does the text come from for the page that flashes on failed HTTPS attempts?

### ISSUE THREAD

**Issue by Gitoffthelawn** [claustromaniac/httpz#14]
I'm sure you are aware that there is a page filled with messages in a large font that sometimes momentarily appears when HTTPZ unsuccessfully tries to load a page through HTTPS.

Where do those strings come from?  Can we edit them somehow?

**Comment by claustromaniac** [comment]
That's the cosmetic issue mentioned in the readme.

Other than using a custom `userChrome.css`, I'm not sure if there is any easy way to edit them. I wouldn't recommend doing substantial changes to it anyway because that would affect all other instances when Firefox displays those errors. Moreover, even if you try to "fix" that issue with a custom `userChrome.css`, it likely won't work, because the cause would remain: the extension does not give Firefox enough time to finish loading that error page (and so it won't give it time for applying the changes from `userChrome.css` either).

**Comment by Gitoffthelawn** [comment]
Thanks.  So it's the FF-generated HTTPS error page that gets interrupted while it is rendering, thus showing all the possible errors?

**Comment by claustromaniac** [comment]
Yup. They're not all the possible errors, though. There are others that appear as warnings and such.

**Comment by Gitoffthelawn** [comment]
Thank you for the details.  Much appreciated.  Closing now.
