### ISSUE TITLE
Confusing page loading sequence in 0.7.1

### ISSUE THREAD

**Issue by Gitoffthelawn** [claustromaniac/httpz#15]
Faster to show than to explain.

STR:
1. Create a bookmark to http://blog.bahraniapps.com/gifcam/
2. Make sure you have at least one more bookmark
3. Open FF's Bookmark Library
4. Open the bookmark created in step 1 by double-clicking on it
5. Within a few seconds, open another bookmark my double-clicking on it
6. Notice that bookmark opened in step 5 gets replaced by the site opened in step 4

This makes sense when you understand what HTTPZ is doing behind the scenes, but is definitely unexpected behavior if you don't.

**Comment by claustromaniac** [comment]
Yeah. Happens because the first request is interrupted by yourself when you double click the second bookmark, and this fires the event that redirects requests on error. There are many other possible instances of such unexpected behavior (for example when another extension aborts a request), and I am aware of some things I can do to fix them. I may end up having to make exceptions for certain types of errors, but I'm afraid that may introduce other potential issues. 

I'll see what I can do.
