### ISSUE TITLE
Hybrid Engine 

### ISSUE THREAD

**Issue by ghost** [claustromaniac/httpz#35]
I think is good, add an feature to use HTTPS Everywhere database, so, if the site is on db, do not TRY HTTPS, if isn't on db, then TRY, this feature can be optional, and db can be auto updated like HTTPS Everywhere. What you think?

**Comment by ghost** [comment]
in my ff 67 have an bug, if I open 10 sites for instance, my cpu go to 100% and do not back, locked in 100%, disable the addon, solved!

**Comment by claustromaniac** [comment]
If I understand your feature suggestion correctly, installing both HTTPZ and HTTPS Everywhere should already achieve that behavior.

As for your second comment: this extension does not perform any kind of CPU-intensive tasks, so I don't have any idea of what could be causing what you describe (assuming I understand). Please, [open a new issue](https://github.com/claustromaniac/httpz/issues/new) and provide detailed steps to reproduce your problem.

**Comment by ghost** [comment]
HTTPZ and HTTPS Everywhere can work together perfectly, for instance HTTPZ can't TRY HTTP before the HTTPS Everywhere action?

About CPU, I just enable the plugin, if open for instance 10 tabs, my cpu go to 100% and still in 100%, if I disable the plugin, fix!

**Comment by claustromaniac** [comment]
> HTTPZ and HTTPS Everywhere can work together perfectly, for instance HTTPZ can't TRY HTTP before the HTTPS Everywhere action?

I did not confirm this myself (which is why I do not go out of my way to advertise HTTPZ as compatible with HTTPS Everywhere), but the mandatory use of WebExtensions APIs and my experience with them allow me to make predictions without actually testing this particular combination. To elaborate:

1. you navigate to http://not.in.httpseverywheres.database/
2. `onBeforeRequest` event handlers fire in order (pretty sure it's the extensions' install order)
   - **2a** HTTPZ was installed first: it redirects the request to HTTPS, 
     - this hypothetical site does not support HTTPS, so HTTPZ falls back to HTTP, and HTTPS Everywhere does not know about this site, so it does not touch the request
	 - the site supports HTTPS, so it loads. Nothing else happens
   - **2b** HTTPS Everywhere was installed first: since the site is not in its database it ignores it, and then HTTPZ takes over from there (see 2a)
3. you navigate to http://in.https.everywheres.database/
4. `onBeforeRequest` event handlers fire in order...
   - **4a** HTTPZ installed first: it redirects the request to HTTPS
     - if the site loads successfully (as it should), nothing else happens
     - if the page does not load because of, for example, a network error, HTTPZ falls back to HTTP (and ignores subsequent requests to that host), and then HTTPS Everywhere kicks in and redirects the request again to HTTPS (which may or may not end in yet another error)
   - **4b** HTTPS Everywhere installed first: the site is known to work over HTTPS by HTTPS Everywhere, so the request is redirected to HTTPS, and HTTPZ doesn't touch it regardless of the outcome (because it never gets to see the first request made over HTTP)
  
> About CPU, I just enable the plugin, if open for instance 10 tabs, my cpu go to 100% and still in 100%, if I disable the plugin, fix!

Well, I've never seen that behavior myself, and I can't imagine what could be causing that on your end because, as stated above, HTTPZ does not perform any kind of CPU-intensive tasks that could lead to that. 

If you want me to look into that, you're going to have to be more specific. What version of HTTPZ are you using? have you tested this in a brand new profile to make sure the problem comes from HTTPZ and not from somewhere else? did you check `about:performance` to confirm the one hogging your CPU is HTTPZ? did you load the 10 sites sequentially or simultaneously? if you loaded them at the same time, how exactly did you do that? does the problem occur no matter *which* sites you try to load? are you sure the problem is not caused by one of those sites instead?

I mean, without more info, there is nothing for me to do. Also, if you finally decide to provide some more info, please do so in a new issue, as requested. Thanks in advance.

**Comment by ghost** [comment]
ok , thanks , I can do this tests
