### ISSUE TITLE
add advanced options / expert mode

### ISSUE THREAD

**Issue by claustromaniac** [claustromaniac/httpz#39]
Another one for the back burner. 

I think some options are worth clustering into an "advanced" section.

**Comment by Madis0** [comment]
I think you could just rephrase the options for now (where and if needed) but when you do add advanced options, place everything that is anti-automatic mode to it. #28 is related

**Comment by grahamperrin** [comment]
This probably falls under the umbrella of _advanced_: 

1. switch to manual
2. <http://www.macattorney.com/upos.html>
3. observe the HTTPZ error page
4. proceed with `http`
5. wonder about the details of the error
6. manually visit <https://www.macattorney.com/upos.html>
7. observe the HTTPZ error page
8. quit, start Firefox
9. manually visit <https://www.macattorney.com/upos.html>
10. observe a traditional yellow alert
11. click **Advanced…**
12. observe the details (in this case, SSL_ERROR_BAD_CERT_DOMAIN). 

On one hand there is … let's say, sometimes, the wish to proceed to the browser's integral page i.e. 

> ### Warning: Potential Security Risk Ahead

– instead of proceeding with `http`. 

On the other hand, from <https://github.com/claustromaniac/httpz/issues/28#issuecomment-557116700>: 

> … informing the precise reason requires additional unnecessary processing, … code complexity that would not even necessarily stand the test of time well (= more maintenance). …

**Comment by grahamperrin** [comment]
Incidentally, in praise of the extension: 

https://github.com/claustromaniac/httpz/commit/ad961b137ccabab67b1406b25a71e282574d79e0#diff-0730bb7c2e8f9ea2438b52e419dd86c9R14

> … HTTPZ does not wait for Firefox to finish loading those error pages, …  causes them to load partially, …

From this description, I imagined finding a visibly incomplete error page, or the browser's internal page somehow mangled with an HTTPZ page. It wasn't until I began testing with a heavily extended profile that I noticed the occasional _split-second_ presentation of an internal page. 

I mean, the word _partial_ made me imagine something ugly or incomplete when in fact (unless I'm missing something) the end result is a clean and tidy HTTPZ error page. Maybe use some other word? Here in GitHub and at AMO. 

Just a thought `:-)`

**Comment by claustromaniac** [comment]
@grahamperrin 

It's not as complicated to show the type of error (like `SSL_ERROR_BAD_CERT_DOMAIN`). In fact, HTTPZ already shows that information in the console. Adding that information to the error page in manual mode is not a bad idea, but it won't be as complete as in Firefox's own error pages.

> the end result is a clean and tidy HTTPZ error page

That's one of the secondary advantages of the manual mode. Firefox takes very little time to load and render the extension's error page, but in automatic mode those messages (the ones from Firefox) are way more noticeable. Not always though.

**Comment by claustromaniac** [comment]
Thanks for the feedback. I tried to add this in [`0.11.0b3`](https://github.com/claustromaniac/httpz/releases), but observations/objections/ideas are still welcome.
